runtime: go111
instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 1m

handlers:
  - url: /(robots\.txt)
    static_files: \1
    upload: (robots\.txt)
  - url: /docs # this redirects back to root
    script: auto
  - url: /api
    script: auto
  - url: /(.*\.(html|css|ico))$
    static_files: docs/\1
    upload: docs/.*
  - url: /
    script: auto
